default_language_version:
    python: python3.11

repos:
  - repo: local
    hooks:

      - id: absolufy-imports
        name: absolufy-imports
        entry: absolufy-imports
        language: python
        types: [ python ]
        args: [
          "--application-directories",
          ":app:aio",
        ]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [ python ]
